# Generated by Django 5.1 on 2024-11-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='user',
        ),
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='module', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
