# Generated by Django 5.1 on 2024-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_module_user_module_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(default=1, upload_to='auth_app/images'),
            preserve_default=False,
        ),
    ]
